WebApplication/Controllers/SemesterController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using WebApplication.Models;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace WebApplication.Controllers
{
    public class SemesterController : Controller
    {
        // GET: Semester        
        public async Task<ActionResult> Index()
        {
            string fileURL = ConfigurationManager.AppSettings["RequestPath"];
            ViewBag.semesters = await Models.Semester.GetCollectionAsync();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(Semester semester)
        {
            bool result = await semester.Push();
            if (result)
                return Redirect("Index");
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpGet]
        public async Task<ActionResult> Del(string ID)
        {
            Semester semester = new Semester();
            semester.ID = ID;
            if (semester?.Delete() ?? false)
                return Redirect("/Semester");
            else
                return View("~/Views/Shared/Error.cshtml");
        }
        [HttpPost] //
        public async Task<ActionResult> Up(Semester semester)
        {
            if (await semester.Update())
                return Redirect("/Index");
            else
                return View("~/Views/Shared/Error.cshtml");
        }
        [HttpGet] 
        public async Task<ActionResult> Up(string ID)
        {
            Semester semester = await Models.Semester.GetInstanceAsync(ID);
            if (semester == null)
                return View("~/Views/Shared/Error.cshtml");
            semester.ID = ID;
            ViewBag.semester = semester; //запись полей
            return View();
        }
        public async Task<ActionResult> Semester(string ID, string gId)
        {
            if (ID != null)
            {
                Semester semester = await Models.Semester.GetInstanceAsync(ID);
                ViewBag.semester = semester;
                //var students = await Student.GetCollectionAsync(ID, gId);
                //students = students.FindAll(x => x.SemesterId == semester.ID);
                //ViewBag.students = students;
                return View("Look");
            }
            else return View("~/Views/Shared/Error.cshtml");
    }        
    }
}

WebApplication/Views/Semester/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Семестры</title>
</head>
<body>   
    <table class="table table-hover">
        <tr>
            <th>Семестр</th>
            <th>Действие</th>
        </tr>
        @if (ViewBag.semesters != null)
        {
            foreach (var semester in ViewBag.semesters)
            {
                <tr>
                    <td><a href="/Semester/Semester/@semester.ID">@semester.Name</a></td>
                    <td><a href="/Semester/Del/@semester.ID" class="btn btn-primary btn-danger">Удалить</a></td>
                </tr>
            }
        }
    </table>
    <div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="Add" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="AddLabel">Добавление семестра</h3>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm("Add", "Semester", FormMethod.Post))
                    {
                    <div class="form-group">
                        <label for="Abbreviation">Название</label>
                        <input type="text" class="form-control" id="Abbreviation" name="Name" placeholder="Название">
                        <label for="StartDate">StartDate</label>
                        <input type="date" class="form-control" id="StartDate" name="StartDate" aria-describedby="StartDate">
                        <label for="EndDate">EndDate</label>
                        <input type="date" class="form-control" id="EndDate" name="EndDate" aria-describedby="EndDate">
                        <label for="SessionStart">SessionStart</label>
                        <input type="date" class="form-control" id="SessionStart" name="SessionStart" aria-describedby="SessionStart">
                        <label for="SessionEnd">SessionEnd</label>
                        <input type="date" class="form-control" id="SessionEnd" name="SessionEnd" aria-describedby="SessionEnd">
                    </div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                            <button type="submit" class="btn btn-primary">Добавить</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>    
    <ul class="nav navbar-nav navbar-right">
        <li><a class="btn btn-block btn-lg" data-toggle="modal" data-target="#Add">Добавить &equiv;</a></li>
    </ul>
</body>
</html>

WebApplication/Views/Semester/Look.cshtml
@{
    ViewBag.Title = "Look";
}
    <div class="row">
        
        <div class="col-md-7">
            @if (ViewBag.semester != null)
    {
        <p><h1>@ViewBag.semester.Name</h1></p>
        <p><h2>Дата начала: @ViewBag.semester.StartDate</h2></p>
        <p><h2>Дата конца: @ViewBag.semester.EndDate</h2></p>
        <p><h2>Дата начала сессии: @ViewBag.semester.SessionStart</h2></p>
        <p><h2>Дата конца сессии: @ViewBag.semester.SessionEnd</h2></p>
        <p><a href="/Semester/Up/@ViewBag.semester.ID" class="btn btn-primary">Изменить</a></p>
}
        </div>
        @*  *@
        <div class="col-md-3">
            <div><p><h2>Студенты</h2></p></div>
            <div class="row">
                <p>@Html.ActionLink("Студент 1", "About", "Home")</p>
                <p>@Html.ActionLink("Студент 2", "About", "Home")</p>
            </div>            
        </div>
        @*<form>            
            <p><h2>Добавить</h2></p>
            <p><label>ФИО</label>
            <input type="text" /></p> 
            <button>Добавить</button>
        </form>*@
    </div>

WebApplication/Views/Semester/Up.cshtml
@{
    ViewBag.Title = "Up";
}

@using (Html.BeginForm("Up", "Semester", FormMethod.Post))
{
    <label for="Name">Название</label>
    <input type="text" class="form-control" id="Name" name="Name" aria-describedby="name" placeholder="Введите название"
           value="@ViewBag.semester.Name" />
    <label for="StartDate">Дата начала</label>
    <input type="date" class="form-control" id="StartDate" name="StartDate" aria-describedby="StartDate" placeholder="Выберете дату начала"
           value="@ViewBag.semester.StartDate" />
    <label for="EndDate">Дата конца</label>
    <input type="date" class="form-control" id="EndDate" name="EndDate" aria-describedby="EndDate" placeholder="Выберете дату конца"
           value="@ViewBag.semester.EndDate" />
    <label for="SessionStart">Дата начала сессии</label>
    <input type="date" class="form-control" id="SessionStart" name="SessionStart" aria-describedby="SessionStart" placeholder="Выберете дату начала сессии"
           value="@ViewBag.semester.SessionStart" />
    <label for="SessionEnd">Дата конца сессии</label>
    <input type="date" class="form-control" id="SessionEnd" name="SessionEnd" aria-describedby="SessionEnd" placeholder="Выберете дату конца сессии"
           value="@ViewBag.semester.SessionEnd" />
    <input type="hidden" value="@ViewBag.semester.ID" />
    <input type="submit" class="btn btn-submit" value="Изменить" />
}