WebApplication/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using WebApplication.Models;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace WebApplication.Controllers
{
    public class GroupController : Controller
    {
        // GET: Group
        public async Task<ActionResult> Index()
        {
            string fileURL = ConfigurationManager.AppSettings["RequestPath"];
            ViewBag.groups = await Models.Group.GetCollectionAsync();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(Group group)
        {
            bool result = await group.Push();
            //if(result)
                return Redirect(Request.UrlReferrer.ToString());
            //else
            //    return View("~/Views/Shared/Error.cshtml");
        }

        [HttpPost]
        public async Task<ActionResult> AddToSemester(string id, string semesterid)
        {
            Group group = await Models.Group.GetInstanceAsync(id);
            if(group == null)
                return View("~/Views/Shared/Error.cshtml");

            Semester semester = await Semester.GetInstanceAsync(semesterid);
            if(semester == null)
                return View("~/Views/Shared/Error.cshtml");

            bool result = await group.AddToSemester(id, semesterid);
            return Redirect(String.Format("/Group/Group/{0}",id));
        }

        [HttpPost]
        public async Task<ActionResult> DeleteToSemester(string id, string semesterid)
        {
            Group group = await Models.Group.GetInstanceAsync(id);
            if(group == null)
                return View("~/Views/Shared/Error.cshtml");

            Semester semester = await Semester.GetInstanceAsync(semesterid);
            if(semester == null)
                return View("~/Views/Shared/Error.cshtml");

            if(group.DeleteToSemester(id, semesterid))
                return Redirect(String.Format("/Group/Group/{0}", id));
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpGet]
        public async Task<ActionResult> Del(string ID)
        {
            Group group = await Models.Group.GetInstanceAsync(ID);
            group.ID = ID;
            if (group.Delete())
                return Redirect(Request.UrlReferrer.ToString());
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpPost] //
        public async Task<ActionResult> Up(Group group)
        {
            if(await group.Update())
                return Redirect("/Faculty");
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpGet] //по ID cnhfybwf c ajhv
        public async Task<ActionResult> Up(string ID)
        {
            Group group = await Models.Group.GetInstanceAsync(ID);
            if (group == null)
                return View("~/Views/Shared/Error.cshtml");

            ViewBag.group = group; //запись полей
            return View();
        }

        public async Task<ActionResult> Group(string ID)
        {
            if (ID != null)
            {
                Group group = await Models.Group.GetInstanceAsync(ID);
                ViewBag.group = group;
                List<Semester> semesters = await Semester.GetCollectionAsync();
                semesters = semesters.Except(group.Semesters).ToList();
                ViewBag.semesters = semesters;
                return View("Look");
            }
            else return View("~/Views/Shared/Error.cshtml");
        }
    }
}

WebApplication/Controllers/LabController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using WebApplication.Models;
using System.Web.Mvc;
using System.Threading.Tasks;
using System.Net.Http;
using System.Net;

namespace WebApplication.Controllers
{
    public class LabController : Controller
    {
        // GET: Lab
        public async Task<ActionResult> Index()
        {
            string fileURL = ConfigurationManager.AppSettings["RequestPath"];
            ViewBag.labs = await Models.Lab.GetCollectionAsync();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(Lab lab, string id)
        {
            bool result = await lab.Push(id);
            if (result)
                return Redirect("/Index");
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpGet]
        public async Task<ActionResult> Del(string ID)
        {
            Lab lab = new Lab();
            lab.ID = ID;
            if (lab?.Delete() ?? false)
                return Redirect("/Lab");
            else
                return View("~/Views/Shared/Error.cshtml");
        }
        [HttpPost] //
        public async Task<ActionResult> Up(Lab lab)
        {
            if (await lab.Update())
                return Redirect("/Lab");
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpGet]
        public async Task<ActionResult> Up(string ID)
        {
            Lab lab = await Models.Lab.GetInstanceAsync(ID);
            if (lab == null)
                ViewBag.lab = lab; //запись полей
            return View();
        }

        [Route("Lab/plan/{fsid}")]
        public async Task<ActionResult> LabPlan(string fsid)
        {
            var subflow = await FlowSubject.GetInstanceAsync(fsid);
            ViewBag.subflow = subflow;
            var workplan = await LabWorkPlan.GetCollectionAsync(fsid);
            ViewBag.workplan = workplan;
            var works = await Models.Lab.GetCollectionAsync();
            ViewBag.works = works;
            return View("PlanLab");
        }

        [HttpPost]
        [Route("Lab/plan")]
        public async Task<ActionResult> AddLabPlan(LabWorkPlan plan)
        {
            if (plan == null)
                return View("~/Views/Shared/Error.cshtml");

            if (await plan.Push())
                return Redirect(string.Format("/Lab/plan/{0}", plan.FlowSubjectId));
            else
                return View("~/Views/Shared/Error.cshtml");
        }
        //Удалить лаб раб из плана
        [HttpPost]
        [Route("Lab/plan/{id}")]
        public async Task<ActionResult> DeleteLabPlan(string id)
        {
            LabWorkPlan plan = new LabWorkPlan
            {
                ID = id
            };
            if (plan.DeleteOfPlan())
                return Redirect(Request.UrlReferrer.ToString());
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        // получить список выполненных студентом лаб работ по предмету (все рег. пользователи)
        [HttpGet]
        [Route("Lab/exec/{studentFlowId}/{subjectFlowId}")]
        public async Task<ActionResult> GetExec(string studentFlowId, string subjectFlowId)
        {
            
            FlowSubject fSubject = await FlowSubject.GetInstanceAsync(subjectFlowId);
            var exLabs = await ExecutedLabWork.GetExec(studentFlowId);
            var workPlan = await LabWorkPlan.GetCollectionAsync(subjectFlowId);

            if (fSubject == null)
                return View("~/Views/Shared/Error.cshtml");

            ViewBag.exLabs = exLabs;
            ViewBag.fSubject = fSubject;
            ViewBag.workPlan = workPlan;
            ViewBag.studentFlowId = studentFlowId;
            return View("LabWorkStudent");
        }

        // установить лаб работу из плана как выполненную студентом (преподаватель, администратор)
        [HttpPost]
        [Route("Lab/exec")]
        public async Task<ActionResult> PostExec(ExecutedLabWork exLab)
        {
            if(exLab == null)
                return View("~/Views/Shared/Error.cshtml");

            if (await exLab.AddExec())
                return Redirect(Request.UrlReferrer.ToString());
            else
                return View("~/Views/Shared/Error.cshtml");
        }
        public async Task<ActionResult> Lab(string ID)
        {
            if (ID != null)
            {
                Lab lab = await Models.Lab.GetInstanceAsync(ID);
                ViewBag.lab = lab;               
                return View("Look");
            }
            else return View("~/Views/Shared/Error.cshtml");
        }
    }
}

WebApplication/Views/Lab/Index.cshtml
@using WebApplication.Models;
@{
    ViewBag.Title = "Index";
}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Факультеты</title>
</head>
<body>
    <table class="table table-hover">
        <tr>
            <th>Лабораторная работа</th>
            <th>Действие</th>
        </tr>

        @if (ViewBag.labs != null)
        {
            foreach (var lab in ViewBag.labs)
            {
                <tr>
                    <td><a href="/Lab/Lab/@lab.ID">@lab.Name</a></td>
                    <td><a href="/Lab/Del/@lab.ID" class="btn btn-primary btn-danger">Удалить</a></td>
                </tr>
            }
        }
    </table>
    <div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="Add" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="AddLabel">Добавление лабораторной работы</h3>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm("Add", "Lab", FormMethod.Post))
                    {
                        <div class="form-group">
                            <label for="Name">Название</label>
                            <input type="text" class="form-control" id="Name" name="Name" placeholder="Название">
                            <label for="Advanced">Информация</label>
                            <input type="text" class="form-control" id="Advanced" name="Advanced" aria-describedby="name" placeholder="Введите описание">
                            <label for="Author">Афтор</label>
                            @{
                                List<Person> people = Person.GetCollectionAsync().Result;
                            }
                            <select id="AddLabel" name="AuthorId">
                                @foreach (var person in people)
                                {
                                    <option value="@person.ID">@person.ToString()</option>
                                }
                            </select>
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                            <button type="submit" class="btn btn-primary">Добавить</button>
                        </div>
                    }
                </div>
            </div>
        </div>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li><a class="btn btn-block btn-lg" data-toggle="modal" data-target="#Add">Добавить &equiv;</a></li>
    </ul>
</body>
</html>

WebApplication/Views/Lab/LabWorkStudent.cshtml
@using WebApplication.Models
@{
    ViewBag.Title = "LabWorkStudent";
}

<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Лабораторные работы</title>
</head>
<body>
    <div class="row">
        <div class="col-md-4">
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th>Название работы</th>
                    </tr>
                </thead>

                @{ 
                    List< ExecutedLabWork> exlabs = ViewBag.exlabs;
                }
                @foreach (var work in (List<LabWorkPlan>)ViewBag.workplan)
                {
                    ExecutedLabWork exWork = exlabs.Find(x => x.PlanId == work.ID);
                    <tr>
                        <td><a href="#">@work.Work.Name</a></td>
                        @if(exWork != null)
                        {
                            <td><font color="green">Выполнена</font></td>
                            @*<td><a href="#" class="btn btn-danger">Снять отметку</a></td>*@
                        }
                        else
                        {
                            <td><font color="red">Не выполнена</font></td>
                            <td>
                                <form action="/Lab/exec" method="post">
                                    <input type="hidden" name="PlanId" value="@work.ID" />
                                    <input type="hidden" name="StudentFlowSubjectId" value="@ViewBag.studentFlowId" />
                                    <input type="submit" value="Отметить" class="btn btn-success" />
                                </form>
                            </td>
                        }
                    </tr>

                }


            </table>
        </div>
      </div>
</body>
</html>

WebApplication/Views/Lab/Look.cshtml
@{
    ViewBag.Title = "Look";
}
<div class="row">
    <div class="col-md-7">
        @if (ViewBag.lab != null)
        {
            <p><h1>@ViewBag.lab.Name</h1></p>
            <p>@ViewBag.lab.Advanced</p>
            <tr>
                <td><a href="/Lab/Up/@ViewBag.lab.ID" class="btn btn-primary">Изменить</a></td>
            </tr>
        }
    </div>
    @*<div class="col-md-3">
                        @if (ViewBag.groups != null)
                    {
                        <p><h2>Группы: </h2></p>
                    foreach (var group in ViewBag.groups)
                    {
                        <p>
                            <a href="/Group/Group/@group.ID" class="btn btn-primary">@group.Name</a>
                            <a href="/Group/Del/@group.ID" class="btn btn-primary btn-danger">Удалить</a>
                        </p>
                }
                }
                    <div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="Add" aria-hidden="true">
                                <div class="modal-dialog modal-sm" role="document">
                                    <div class="modal-content">
                                        <div class="modal-header">
                                            <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                                            <span aria-hidden="true">&times;</span>
                                        </button>
                                        <h3 class="modal-title" id="AddLabel">Добавление группы</h3>
                                    </div>
                                        <div class="modal-body">
                                            @using (Html.BeginForm("Add", "Group", FormMethod.Post))
                        {
                                        <div class="form-group">
                                            <label for="Name">Название</label>
                                            <input type="text" class="form-control" id="Name" name="Name" placeholder="Введите название">

                                            <label for="Description">Описание</label>
                                            <input type="text" class="form-control" id="Description" name="Description" aria-describedby="Description" placeholder="Введите описание">

                                            <input type="hidden" name="FacultyId" value="@ViewBag.faculty.ID" />
                                            <label for="CuratorId">Curator</label>
                                            <input type="text" class="form-control" id="CuratorId" name="CuratorId" aria-describedby="CuratorId" placeholder="">
                                        </div>
                                        <div class="modal-footer">
                                            <button class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                            <button type="submit" class="btn btn-primary">Добавить</button>
                                        </div>
                    }
                                        </div>
                                    </div>
                                </div>
                            </div>
                        <ul class="nav navbar-nav navbar-right">
                                        <li><a class="btn btn-block btn-lg" data-toggle="modal" data-target="#Add">Добавить &equiv;</a></li>
                                    </ul>
        </div>*@
</div>

WebApplication/Views/Lab/PlanLab.cshtml
@using WebApplication.Models
@{
    ViewBag.Title = "PlanLab";
}

<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Факультеты</title>
</head>
<body>
    <div class="row">
        @{ FlowSubject subflow = ViewBag.subflow; }
        <div class="col-md-4">
            @{ Subject subject = Subject.GetInstanceAsync(subflow.SubjectId).Result; }
            <p><h3>План лабораторных работ</h3></p>
            <p>Предмет: @subject.Name</p>
        </div>
        <div class="col-md-4">
            @{ Flow flow = Flow.GetInstanceAsync(subflow.FlowId).Result; }
            <p><h3>@flow.Name</h3></p>
            <p>@flow.AltName</p>
        </div>
    </div>
    <div class="row">
        <table class="table table-hover">
            <thead>
                <tr>
                    <th>Название работы</th>
                    @*<th>% выполнивших</th>*@
                </tr>
            </thead>
            @foreach (var work in (List<LabWorkPlan>)ViewBag.workplan)
            {
                <tr>
                    <td><a href="/Lab/Lab/@work.Work.ID">@work.Work.Name</a></td>@*здесь переход к странице лаб работы*@
                    @*<td><a href="/Student/@subflow.ID/labwork">0%</a></td>*@ @*здесь переход к студентам, выполнившим лаб. работу*@
                    @*<td><a href="/Lab/plan/DeleteLabPlan/@work.ID" class="btn btn-danger">Удалить из плана</a></td>*@
                </tr>
            }
        </table>
     </div>
    @*<div class="row">
        @Html.BeginForm()
        @using (Html.BeginForm("AddLabPlan", "Lab", FormMethod.Post))
        {
            <label for="work">Лабораторная работа</label>
            <select class="form-control" id="work" name="WorkId">
                @foreach (var work in ViewBag.works)
                {
                    <option value="@work.ID">@work.Name</option>
                }
            </select>
            <input type="hidden" name="FlowSubjectId" value="@subflow.ID" />
            <input type="submit" class="btn btn-success" value="Добавить в план" />
        }
    </div>*@
    <div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="Add" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="AddLabel">Добавление лабораторной</h3>
                </div>
                <div class="modal-body">
                    <form action="/Lab/plan" method="post">
                        <div class="form-group">
                            <label for="work">Лабораторная работа</label>
                            <select class="form-control" id="work" name="WorkId">
                                @foreach (var work in ViewBag.works)
                                {
                                    <option value="@work.ID">@work.Name</option>
                                }
                            </select>

                            <input type="hidden" name="FlowSubjectId" value="@subflow.ID" />
                        </div>
                        <div class="modal-footer">
                            <button class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                            <button type="submit" class="btn btn-primary">Добавить</button>
                        </div>
                    </form>
                    @*@using (Html.BeginForm("AddLabPlan", "Lab", FormMethod.Post))
                    {
                        <div class="form-group">
                            <label for="work">Лабораторная работа</label>
                            <select class="form-control" id="work" name="WorkId">
                                @foreach(var work in ViewBag.works)
                                {
                                    <option value="@work.ID">@work.Name</option>
                                }
                            </select>
                            
                            <input type="hidden" name="FlowSubjectId" value="@subflow.ID" />
                        </div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                    }*@
                </div>
            </div>
        </div>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <li><a class="btn btn-block btn-lg" data-toggle="modal" data-target="#Add">Добавить &equiv;</a></li>
    </ul>
</body>
</html>

WebApplication/Views/Lab/Up.cshtml
@{
    ViewBag.Title = "Up";
}

@using (Html.BeginForm("Up", "Lab", FormMethod.Post))
{
    <label for="Name">Название</label>
    <input type="text" class="form-control" id="Name" name="Name" aria-describedby="name" placeholder="Введите название"
           value="@ViewBag.lab.Name" />
       <label for="Advanced">Описание</label>   
       <input type="text" class="form-control" id="Advanced" name="Advanced" aria-describedby="info" placeholder="Введите название"
           value="@ViewBag.lab.Advanced" />
       <input type="hidden" value="@ViewBag.lab.ID" />
       <input type="submit" class="btn btn-submit" value="Изменить" />
}