WebApplication/Controllers/FacultyController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using WebApplication.Models;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace WebApplication.Controllers
{
    public class FacultyController : Controller
    {
        // GET: Faculty
        public async Task<ActionResult> Index()
        {
            string fileURL = ConfigurationManager.AppSettings["RequestPath"];
            ViewBag.faculties = await Models.Faculty.GetCollectionAsync();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(Faculty faculty)
        {
            bool result = await faculty.Push();
            if (result)
                return Redirect("/Faculty");
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpGet]
        public async Task<ActionResult> Del(string ID)
        {
            Faculty faculty = new Faculty();
            faculty.ID = ID;
            if (faculty?.Delete() ?? false)
                return Redirect("/Faculty");
            else
                return View("~/Views/Shared/Error.cshtml");
        }
        [HttpPost] //
        public async Task<ActionResult> Up(Faculty faculty)
        {
            if (await faculty.Update())
                return Redirect("/Faculty");
            else
                return View("~/Views/Shared/Error.cshtml");
        }
        [HttpGet] //по ID cnhfybwf c ajhv
        public async Task<ActionResult> Up(string ID)
        {
            Faculty faculty = await Models.Faculty.GetInstanceAsync(ID);
            if (faculty == null)
                return View("~/Views/Shared/Error.cshtml");
            ViewBag.faculty = faculty; //запись полей
            return View();
        }
        public async Task<ActionResult> Faculty(string ID)
        {
            if (ID != null)
            {
                Faculty faculty = await Models.Faculty.GetInstanceAsync(ID);
                ViewBag.faculty = faculty;
                var groups = await Group.GetCollectionAsync();
                groups = groups.FindAll(x => x.FacultyId == faculty.ID);
                ViewBag.groups = groups;
                return View("Look");
            }
            else return View("~/Views/Shared/Error.cshtml");
        }        
    }
}

WebApplication/Controllers/GroupController.cs
using System;
using System.Collections.Generic;
using System.Configuration;
using System.Linq;
using System.Web;
using WebApplication.Models;
using System.Web.Mvc;
using System.Threading.Tasks;

namespace WebApplication.Controllers
{
    public class GroupController : Controller
    {
        // GET: Group
        public async Task<ActionResult> Index()
        {
            string fileURL = ConfigurationManager.AppSettings["RequestPath"];
            ViewBag.groups = await Models.Group.GetCollectionAsync();
            return View();
        }

        [HttpPost]
        public async Task<ActionResult> Add(Group group)
        {
            bool result = await group.Push();
            //if(result)
                return Redirect(Request.UrlReferrer.ToString());
            //else
            //    return View("~/Views/Shared/Error.cshtml");
        }

        [HttpPost]
        public async Task<ActionResult> AddToSemester(string id, string semesterid)
        {
            Group group = await Models.Group.GetInstanceAsync(id);
            if(group == null)
                return View("~/Views/Shared/Error.cshtml");

            Semester semester = await Semester.GetInstanceAsync(semesterid);
            if(semester == null)
                return View("~/Views/Shared/Error.cshtml");

            bool result = await group.AddToSemester(id, semesterid);
            return Redirect(String.Format("/Group/Group/{0}",id));
        }

        [HttpPost]
        public async Task<ActionResult> DeleteToSemester(string id, string semesterid)
        {
            Group group = await Models.Group.GetInstanceAsync(id);
            if(group == null)
                return View("~/Views/Shared/Error.cshtml");

            Semester semester = await Semester.GetInstanceAsync(semesterid);
            if(semester == null)
                return View("~/Views/Shared/Error.cshtml");

            if(group.DeleteToSemester(id, semesterid))
                return Redirect(String.Format("/Group/Group/{0}", id));
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpGet]
        public async Task<ActionResult> Del(string ID)
        {
            Group group = await Models.Group.GetInstanceAsync(ID);
            group.ID = ID;
            if (group.Delete())
                return Redirect(Request.UrlReferrer.ToString());
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpPost] //
        public async Task<ActionResult> Up(Group group)
        {
            if(await group.Update())
                return Redirect("/Faculty");
            else
                return View("~/Views/Shared/Error.cshtml");
        }

        [HttpGet] //по ID cnhfybwf c ajhv
        public async Task<ActionResult> Up(string ID)
        {
            Group group = await Models.Group.GetInstanceAsync(ID);
            if (group == null)
                return View("~/Views/Shared/Error.cshtml");

            ViewBag.group = group; //запись полей
            return View();
        }

        public async Task<ActionResult> Group(string ID)
        {
            if (ID != null)
            {
                Group group = await Models.Group.GetInstanceAsync(ID);
                ViewBag.group = group;
                List<Semester> semesters = await Semester.GetCollectionAsync();
                semesters = semesters.Except(group.Semesters).ToList();
                ViewBag.semesters = semesters;
                return View("Look");
            }
            else return View("~/Views/Shared/Error.cshtml");
        }
    }
}

WebApplication/Views/Faculty/Index.cshtml
@{
    ViewBag.Title = "Index";
}
<!DOCTYPE HTML>
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <title>Факультеты</title>
</head>
<body>
    <table class="table table-hover">
        <tr>
            <th>Факультет</th>
            <th>Действие</th>
        </tr>
        @if (ViewBag.faculties != null)
    {
        foreach (var faculty in ViewBag.faculties)
        {
            <tr>
                <td><a href="/Faculty/Faculty/@faculty.ID">@faculty.Name</a></td>
                <td><a href="/Faculty/Del/@faculty.ID" class="btn btn-primary btn-danger">Удалить</a></td>
            </tr>
    }
}
    </table>
    <div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="Add" aria-hidden="true">
        <div class="modal-dialog modal-sm" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                    <h3 class="modal-title" id="AddLabel">Добавление факультета</h3>
                </div>
                <div class="modal-body">
                    @using (Html.BeginForm("Add", "Faculty", FormMethod.Post))
    {
                <div class="form-group">
                    <label for="Abbreviation">Аббревиатура</label>
                    <input type="text" class="form-control" id="Abbreviation" name="Name" placeholder="Аббревиатура">
                
                    <label for="FullName">Описание</label>
                    <input type="text" class="form-control" id="FullName" name="Info" aria-describedby="name" placeholder="Введите описание">
                </div>
                <div class="modal-footer">
                    <button class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                    <button type="submit" class="btn btn-primary">Добавить</button>
                </div>
}
                </div>
                </div>                
            </div>
        </div>
    <ul class="nav navbar-nav navbar-right">
                    <li><a class="btn btn-block btn-lg" data-toggle="modal" data-target="#Add">Добавить &equiv;</a></li>
                </ul>
</body>
</html>

WebApplication/Views/Faculty/Look.cshtml
@using WebApplication.Models;
@{
    ViewBag.Title = "Look";
}
<div class="row">
    <div class="col-md-7">
        @if (ViewBag.faculty != null)
        {
            <p><h1>@ViewBag.faculty.Name</h1></p>
            @*<p><h2>Декан: @ViewBag.faculty.DekanId</h2></p>*@
            <p>@ViewBag.faculty.Info</p>
            <tr>
                <td><a href="/Faculty/Up/@ViewBag.faculty.ID" class="btn btn-primary">Изменить</a></td>
            </tr>
        }
    </div>
    <div class="col-md-3">
        @if (ViewBag.groups != null)
        {
            <p><h2>Группы: </h2></p>
            foreach (var group in ViewBag.groups)
            {
                <p>
                    <a href="/Group/Group/@group.ID">@group.Name</a>
                    <a href="/Group/Del/@group.ID" class="btn btn-primary btn-danger">Удалить</a>
                </p>
            }
        }
        <div class="modal fade" id="Add" tabindex="-1" role="dialog" aria-labelledby="Add" aria-hidden="true">
            <div class="modal-dialog modal-sm" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button class="close" type="button" data-dismiss="modal" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                        <h3 class="modal-title" id="AddLabel">Добавление группы</h3>
                    </div>
                    <div class="modal-body">
                        @using (Html.BeginForm("Add", "Group", FormMethod.Post))
                        {
                            <div class="form-group">
                                <label for="Name">Название</label>
                                <input type="text" class="form-control" id="Name" name="Name" required placeholder="Введите название">

                                <label for="Description">Описание</label>
                                <input type="text" class="form-control" id="Description" name="Description" placeholder="Введите описание">

                                <input type="hidden" name="FacultyId" value="@ViewBag.faculty.ID" />
                                <label for="CuratorId">Curator</label>
                                @{
                                    List<Person> people = Person.GetCollectionAsync().Result;
                                }
                                <select id="AddLabel" name="CuratorId">
                                    @foreach (var person in people)
                                    {
                                        <option value="@person.ID">@person.ToString()</option>
                                    }
                                </select>
                            </div>
                            <div class="modal-footer">
                                <button class="btn btn-secondary" data-dismiss="modal">Закрыть</button>
                                <button type="submit" class="btn btn-primary">Добавить</button>
                            </div>
                        }
                    </div>
                </div>
            </div>
        </div>
        <ul class="nav navbar-nav navbar-right">
            <li><a class="btn btn-block btn-lg" data-toggle="modal" data-target="#Add">Добавить &equiv;</a></li>
        </ul>
    </div>
</div>